import { defineStore } from 'pinia'
import { ref } from 'vue'

export const usePaginationStore = defineStore('paginationStore', () => {
  const heatMetersItems = ref([
      {
        id: 1,
        img: '/src/assets/img/item-page__item-img.png',
        name: 'Задвижка чугунная КНР 30ч39р Ду50 Ру16',
        article: '123456',
        prevPrice: '2 000',
        currPrice: '2 000',
      },
      {
        id: 2,
        img: '/src/assets/img/item-page__item-img.png',
        name: 'Задвижка чугунная КНР 30ч39р Ду50 Ру16',
        article: '123456',
        prevPrice: '2 000',
        currPrice: '2 000',
      },
      {
        id: 3,
        img: '/src/assets/img/item-page__item-img.png',
        name: 'Задвижка чугунная КНР 30ч39р Ду50 Ру16',
        article: '123456',
        prevPrice: '2 000',
        currPrice: '2 000',
      },
      {
        id: 4,
        img: '/src/assets/img/item-page__item-img.png',
        name: 'Задвижка чугунная КНР 30ч39р Ду50 Ру16',
        article: '123456',
        prevPrice: '2 000',
        currPrice: '2 000',
      },
      {
        id: 5,
        img: '/src/assets/img/item-page__item-img.png',
        name: 'Задвижка чугунная КНР 30ч39р Ду50 Ру16',
        article: '123456',
        prevPrice: '2 000',
        currPrice: '2 000',
      },
      {
        id: 6,
        img: '/src/assets/img/item-page__item-img.png',
        name: 'Задвижка чугунная КНР 30ч39р Ду50 Ру16',
        article: '123456',
        prevPrice: '2 000',
        currPrice: '2 000',
      },
      {
        id: 7,
        img: '/src/assets/img/item-page__item-img.png',
        name: 'Задвижка чугунная КНР 30ч39р Ду50 Ру16',
        article: '123456',
        prevPrice: '2 000',
        currPrice: '2 000',
      },
      {
        id: 8,
        img: '/src/assets/img/item-page__item-img.png',
        name: 'Задвижка чугунная КНР 30ч39р Ду50 Ру16',
        article: '123456',
        prevPrice: '2 000',
        currPrice: '2 000',
      },
      {
        id: 9,
        img: '/src/assets/img/item-page__item-img.png',
        name: 'Задвижка чугунная КНР 30ч39р Ду50 Ру16',
        article: '123456',
        prevPrice: '2 000',
        currPrice: '2 000',
      },
      {
        id: 10,
        img: '/src/assets/img/item-page__item-img.png',
        name: 'Задвижка чугунная КНР 30ч39р Ду50 Ру16',
        article: '123456',
        prevPrice: '2 000',
        currPrice: '2 000',
      },
      {
        id: 11,
        img: '/src/assets/img/item-page__item-img.png',
        name: 'Задвижка чугунная КНР 30ч39р Ду50 Ру16',
        article: '123456',
        prevPrice: '2 000',
        currPrice: '2 000',
      },
      {
        id: 12,
        img: '/src/assets/img/item-page__item-img.png',
        name: 'Задвижка чугунная КНР 30ч39р Ду50 Ру16',
        article: '123456',
        prevPrice: '2 000',
        currPrice: '2 000',
      },
      {
        id: 13,
        img: '/src/assets/img/item-page__item-img.png',
        name: 'Задвижка чугунная КНР 30ч39р Ду50 Ру16',
        article: '123456',
        prevPrice: '2 000',
        currPrice: '2 000',
      },
      {
        id: 14,
        img: '/src/assets/img/item-page__item-img.png',
        name: 'Задвижка чугунная КНР 30ч39р Ду50 Ру16',
        article: '123456',
        prevPrice: '2 000',
        currPrice: '2 000',
      },
      {
        id: 15,
        img: '/src/assets/img/item-page__item-img.png',
        name: 'Задвижка чугунная КНР 30ч39р Ду50 Ру16',
        article: '123456',
        prevPrice: '2 000',
        currPrice: '2 000',
      },
      {
        id: 16,
        img: '/src/assets/img/item-page3__item-img.png',
        name: 'Задвижка чугунная КНР 30ч39р Ду50 Ру16',
        article: '123456',
        prevPrice: '1 000',
        currPrice: '1 000',
      },
      {
        id: 17,
        img: '/src/assets/img/item-page3__item-img.png',
        name: 'Задвижка чугунная КНР 30ч39р Ду50 Ру16',
        article: '123456',
        prevPrice: '1 000',
        currPrice: '1 000',
      },
      {
        id: 18,
        img: '/src/assets/img/item-page3__item-img.png',
        name: 'Задвижка чугунная КНР 30ч39р Ду50 Ру16',
        article: '123456',
        prevPrice: '1 000',
        currPrice: '1 000',
      },
      {
        id: 19,
        img: '/src/assets/img/item-page3__item-img.png',
        name: 'Задвижка чугунная КНР 30ч39р Ду50 Ру16',
        article: '123456',
        prevPrice: '1 000',
        currPrice: '1 000',
      },
      {
        id: 20,
        img: '/src/assets/img/item-page3__item-img.png',
        name: 'Задвижка чугунная КНР 30ч39р Ду50 Ру16',
        article: '123456',
        prevPrice: '1 000',
        currPrice: '1 000',
      },
      {
        id: 21,
        img: '/src/assets/img/item-page3__item-img.png',
        name: 'Задвижка чугунная КНР 30ч39р Ду50 Ру16',
        article: '123456',
        prevPrice: '1 000',
        currPrice: '1 000',
      },
      {
        id: 22,
        img: '/src/assets/img/item-page3__item-img.png',
        name: 'Задвижка чугунная КНР 30ч39р Ду50 Ру16',
        article: '123456',
        prevPrice: '1 000',
        currPrice: '1 000',
      },
      {
        id: 23,
        img: '/src/assets/img/item-page3__item-img.png',
        name: 'Задвижка чугунная КНР 30ч39р Ду50 Ру16',
        article: '123456',
        prevPrice: '1 000',
        currPrice: '1 000',
      },
      {
        id: 24,
        img: '/src/assets/img/item-page3__item-img.png',
        name: 'Задвижка чугунная КНР 30ч39р Ду50 Ру16',
        article: '123456',
        prevPrice: '1 000',
        currPrice: '1 000',
      },
      {
        id: 25,
        img: '/src/assets/img/item-page3__item-img.png',
        name: 'Задвижка чугунная КНР 30ч39р Ду50 Ру16',
        article: '123456',
        prevPrice: '1 000',
        currPrice: '1 000',
      },
      {
        id: 26,
        img: '/src/assets/img/item-page3__item-img.png',
        name: 'Задвижка чугунная КНР 30ч39р Ду50 Ру16',
        article: '123456',
        prevPrice: '1 000',
        currPrice: '1 000',
      },
      {
        id: 27,
        img: '/src/assets/img/item-page3__item-img.png',
        name: 'Задвижка чугунная КНР 30ч39р Ду50 Ру16',
        article: '123456',
        prevPrice: '1 000',
        currPrice: '1 000',
      },
      {
        id: 28,
        img: '/src/assets/img/item-page3__item-img.png',
        name: 'Задвижка чугунная КНР 30ч39р Ду50 Ру16',
        article: '123456',
        prevPrice: '1 000',
        currPrice: '1 000',
      },
      {
        id: 29,
        img: '/src/assets/img/item-page3__item-img.png',
        name: 'Задвижка чугунная КНР 30ч39р Ду50 Ру16',
        article: '123456',
        prevPrice: '1 000',
        currPrice: '1 000',
      },
      {
        id: 30,
        img: '/src/assets/img/item-page3__item-img.png',
        name: 'Задвижка чугунная КНР 30ч39р Ду50 Ру16',
        article: '123456',
        prevPrice: '1 000',
        currPrice: '1 000',
      },
      {
        id: 31,
        img: '/src/assets/img/item-page3__item-img.png',
        name: 'Задвижка чугунная КНР 30ч39р Ду50 Ру16',
        article: '123456',
        prevPrice: '1 000',
        currPrice: '1 000',
      },
      {
        id: 32,
        img: '/src/assets/img/item-page3__item-img.png',
        name: 'Задвижка чугунная КНР 30ч39р Ду50 Ру16',
        article: '123456',
        prevPrice: '1 000',
        currPrice: '1 000',
      },
      {
        id: 33,
        img: '/src/assets/img/item-page4__item-img.png',
        name: 'Задвижка чугунная КНР 30ч39р Ду50 Ру16',
        article: '123456',
        prevPrice: '3 000',
        currPrice: '3 000',
      },
      {
        id: 34,
        img: '/src/assets/img/item-page4__item-img.png',
        name: 'Задвижка чугунная КНР 30ч39р Ду50 Ру16',
        article: '123456',
        prevPrice: '3 000',
        currPrice: '3 000',
      },
      {
        id: 35,
        img: '/src/assets/img/item-page4__item-img.png',
        name: 'Задвижка чугунная КНР 30ч39р Ду50 Ру16',
        article: '123456',
        prevPrice: '3 000',
        currPrice: '3 000',
      },
      {
        id: 36,
        img: '/src/assets/img/item-page4__item-img.png',
        name: 'Задвижка чугунная КНР 30ч39р Ду50 Ру16',
        article: '123456',
        prevPrice: '3 000',
        currPrice: '3 000',
      },
      {
        id: 37,
        img: '/src/assets/img/item-page4__item-img.png',
        name: 'Задвижка чугунная КНР 30ч39р Ду50 Ру16',
        article: '123456',
        prevPrice: '3 000',
        currPrice: '3 000',
      },
      {
        id: 38,
        img: '/src/assets/img/item-page4__item-img.png',
        name: 'Задвижка чугунная КНР 30ч39р Ду50 Ру16',
        article: '123456',
        prevPrice: '3 000',
        currPrice: '3 000',
      },
      {
        id: 39,
        img: '/src/assets/img/item-page4__item-img.png',
        name: 'Задвижка чугунная КНР 30ч39р Ду50 Ру16',
        article: '123456',
        prevPrice: '3 000',
        currPrice: '3 000',
      },
      {
        id: 40,
        img: '/src/assets/img/item-page4__item-img.png',
        name: 'Задвижка чугунная КНР 30ч39р Ду50 Ру16',
        article: '123456',
        prevPrice: '3 000',
        currPrice: '3 000',
      },
      {
        id: 41,
        img: '/src/assets/img/item-page4__item-img.png',
        name: 'Задвижка чугунная КНР 30ч39р Ду50 Ру16',
        article: '123456',
        prevPrice: '3 000',
        currPrice: '3 000',
      },
      {
        id: 42,
        img: '/src/assets/img/item-page4__item-img.png',
        name: 'Задвижка чугунная КНР 30ч39р Ду50 Ру16',
        article: '123456',
        prevPrice: '3 000',
        currPrice: '3 000',
      },
      {
        id: 43,
        img: '/src/assets/img/item-page4__item-img.png',
        name: 'Задвижка чугунная КНР 30ч39р Ду50 Ру16',
        article: '123456',
        prevPrice: '3 000',
        currPrice: '3 000',
      },
      {
        id: 44,
        img: '/src/assets/img/item-page4__item-img.png',
        name: 'Задвижка чугунная КНР 30ч39р Ду50 Ру16',
        article: '123456',
        prevPrice: '3 000',
        currPrice: '3 000',
      },
      {
        id: 45,
        img: '/src/assets/img/item-page4__item-img.png',
        name: 'Задвижка чугунная КНР 30ч39р Ду50 Ру16',
        article: '123456',
        prevPrice: '3 000',
        currPrice: '3 000',
      },
      {
        id: 46,
        img: '/src/assets/img/item-page4__item-img.png',
        name: 'Задвижка чугунная КНР 30ч39р Ду50 Ру16',
        article: '123456',
        prevPrice: '3 000',
        currPrice: '3 000',
      },
      {
        id: 47,
        img: '/src/assets/img/item-page4__item-img.png',
        name: 'Задвижка чугунная КНР 30ч39р Ду50 Ру16',
        article: '123456',
        prevPrice: '3 000',
        currPrice: '3 000',
      },
      {
        id: 48,
        img: '/src/assets/img/item-page4__item-img.png',
        name: 'Задвижка чугунная КНР 30ч39р Ду50 Ру16',
        article: '123456',
        prevPrice: '3 000',
        currPrice: '3 000',
      },
    ]),
    articlesItems = ref([
      {
        id: 1,
        img: '/src/assets/img/article1.png',
        date: '01.01.2025',
        text: 'Установка водоизмерительного счётчика: кто должен это делать в муниципальной квартире?',
        read: 'Читать',
      },
      {
        id: 2,
        img: '/src/assets/img/article1.png',
        date: '01.01.2025',
        text: 'Установка водоизмерительного счётчика: кто должен это делать в муниципальной квартире?',
        read: 'Читать',
      },
      {
        id: 3,
        img: '/src/assets/img/article1.png',
        date: '01.01.2025',
        text: 'Установка водоизмерительного счётчика: кто должен это делать в муниципальной квартире?',
        read: 'Читать',
      },
      {
        id: 4,
        img: '/src/assets/img/article1.png',
        date: '01.01.2025',
        text: 'Установка водоизмерительного счётчика: кто должен это делать в муниципальной квартире?',
        read: 'Читать',
      },
      {
        id: 5,
        img: '/src/assets/img/article1.png',
        date: '01.01.2025',
        text: 'Установка водоизмерительного счётчика: кто должен это делать в муниципальной квартире?',
        read: 'Читать',
      },
      {
        id: 6,
        img: '/src/assets/img/article1.png',
        date: '01.01.2025',
        text: 'Установка водоизмерительного счётчика: кто должен это делать в муниципальной квартире?',
        read: 'Читать',
      },
      {
        id: 7,
        img: '/src/assets/img/article1.png',
        date: '01.01.2025',
        text: 'Установка водоизмерительного счётчика: кто должен это делать в муниципальной квартире?',
        read: 'Читать',
      },
      {
        id: 8,
        img: '/src/assets/img/article1.png',
        date: '01.01.2025',
        text: 'Установка водоизмерительного счётчика: кто должен это делать в муниципальной квартире?',
        read: 'Читать',
      },
      {
        id: 9,
        img: '/src/assets/img/article1.png',
        date: '01.01.2025',
        text: 'Установка водоизмерительного счётчика: кто должен это делать в муниципальной квартире?',
        read: 'Читать',
      },
      {
        id: 10,
        img: '/src/assets/img/article1.png',
        date: '01.01.2025',
        text: 'Установка водоизмерительного счётчика: кто должен это делать в муниципальной квартире?',
        read: 'Читать',
      },
      {
        id: 11,
        img: '/src/assets/img/article1.png',
        date: '01.01.2025',
        text: 'Установка водоизмерительного счётчика: кто должен это делать в муниципальной квартире?',
        read: 'Читать',
      },
      {
        id: 12,
        img: '/src/assets/img/article1.png',
        date: '01.01.2025',
        text: 'Установка водоизмерительного счётчика: кто должен это делать в муниципальной квартире?',
        read: 'Читать',
      },
      {
        id: 13,
        img: '/src/assets/img/article1.png',
        date: '01.01.2025',
        text: 'Установка водоизмерительного счётчика: кто должен это делать в муниципальной квартире?',
        read: 'Читать',
      },
      {
        id: 14,
        img: '/src/assets/img/article1.png',
        date: '01.01.2025',
        text: 'Установка водоизмерительного счётчика: кто должен это делать в муниципальной квартире?',
        read: 'Читать',
      },
      {
        id: 15,
        img: '/src/assets/img/article1.png',
        date: '01.01.2025',
        text: 'Установка водоизмерительного счётчика: кто должен это делать в муниципальной квартире?',
        read: 'Читать',
      },
      {
        id: 16,
        img: '/src/assets/img/article1.png',
        date: '01.01.2025',
        text: 'Установка водоизмерительного счётчика: кто должен это делать в муниципальной квартире?',
        read: 'Читать',
      },
      {
        id: 17,
        img: '/src/assets/img/article2.png',
        date: '01.01.2025',
        text: 'Установка водоизмерительного счётчика: кто должен это делать в муниципальной квартире?',
        read: 'Читать',
      },
      {
        id: 18,
        img: '/src/assets/img/article2.png',
        date: '01.01.2025',
        text: 'Установка водоизмерительного счётчика: кто должен это делать в муниципальной квартире?',
        read: 'Читать',
      },
      {
        id: 19,
        img: '/src/assets/img/article2.png',
        date: '01.01.2025',
        text: 'Установка водоизмерительного счётчика: кто должен это делать в муниципальной квартире?',
        read: 'Читать',
      },
      {
        id: 20,
        img: '/src/assets/img/article2.png',
        date: '01.01.2025',
        text: 'Установка водоизмерительного счётчика: кто должен это делать в муниципальной квартире?',
        read: 'Читать',
      },
      {
        id: 21,
        img: '/src/assets/img/article2.png',
        date: '01.01.2025',
        text: 'Установка водоизмерительного счётчика: кто должен это делать в муниципальной квартире?',
        read: 'Читать',
      },
      {
        id: 22,
        img: '/src/assets/img/article2.png',
        date: '01.01.2025',
        text: 'Установка водоизмерительного счётчика: кто должен это делать в муниципальной квартире?',
        read: 'Читать',
      },
      {
        id: 23,
        img: '/src/assets/img/article2.png',
        date: '01.01.2025',
        text: 'Установка водоизмерительного счётчика: кто должен это делать в муниципальной квартире?',
        read: 'Читать',
      },
      {
        id: 24,
        img: '/src/assets/img/article2.png',
        date: '01.01.2025',
        text: 'Установка водоизмерительного счётчика: кто должен это делать в муниципальной квартире?',
        read: 'Читать',
      },
      {
        id: 25,
        img: '/src/assets/img/article2.png',
        date: '01.01.2025',
        text: 'Установка водоизмерительного счётчика: кто должен это делать в муниципальной квартире?',
        read: 'Читать',
      },
      {
        id: 26,
        img: '/src/assets/img/article2.png',
        date: '01.01.2025',
        text: 'Установка водоизмерительного счётчика: кто должен это делать в муниципальной квартире?',
        read: 'Читать',
      },
      {
        id: 27,
        img: '/src/assets/img/article2.png',
        date: '01.01.2025',
        text: 'Установка водоизмерительного счётчика: кто должен это делать в муниципальной квартире?',
        read: 'Читать',
      },
      {
        id: 28,
        img: '/src/assets/img/article2.png',
        date: '01.01.2025',
        text: 'Установка водоизмерительного счётчика: кто должен это делать в муниципальной квартире?',
        read: 'Читать',
      },
      {
        id: 29,
        img: '/src/assets/img/article2.png',
        date: '01.01.2025',
        text: 'Установка водоизмерительного счётчика: кто должен это делать в муниципальной квартире?',
        read: 'Читать',
      },
      {
        id: 30,
        img: '/src/assets/img/article2.png',
        date: '01.01.2025',
        text: 'Установка водоизмерительного счётчика: кто должен это делать в муниципальной квартире?',
        read: 'Читать',
      },
      {
        id: 31,
        img: '/src/assets/img/article2.png',
        date: '01.01.2025',
        text: 'Установка водоизмерительного счётчика: кто должен это делать в муниципальной квартире?',
        read: 'Читать',
      },
      {
        id: 32,
        img: '/src/assets/img/article2.png',
        date: '01.01.2025',
        text: 'Установка водоизмерительного счётчика: кто должен это делать в муниципальной квартире?',
        read: 'Читать',
      },
      {
        id: 33,
        img: '/src/assets/img/article3.png',
        date: '01.01.2025',
        text: 'Установка водоизмерительного счётчика: кто должен это делать в муниципальной квартире?',
        read: 'Читать',
      },
      {
        id: 34,
        img: '/src/assets/img/article3.png',
        date: '01.01.2025',
        text: 'Установка водоизмерительного счётчика: кто должен это делать в муниципальной квартире?',
        read: 'Читать',
      },
      {
        id: 35,
        img: '/src/assets/img/article3.png',
        date: '01.01.2025',
        text: 'Установка водоизмерительного счётчика: кто должен это делать в муниципальной квартире?',
        read: 'Читать',
      },
      {
        id: 36,
        img: '/src/assets/img/article3.png',
        date: '01.01.2025',
        text: 'Установка водоизмерительного счётчика: кто должен это делать в муниципальной квартире?',
        read: 'Читать',
      },
      {
        id: 37,
        img: '/src/assets/img/article3.png',
        date: '01.01.2025',
        text: 'Установка водоизмерительного счётчика: кто должен это делать в муниципальной квартире?',
        read: 'Читать',
      },
      {
        id: 38,
        img: '/src/assets/img/article3.png',
        date: '01.01.2025',
        text: 'Установка водоизмерительного счётчика: кто должен это делать в муниципальной квартире?',
        read: 'Читать',
      },
      {
        id: 39,
        img: '/src/assets/img/article3.png',
        date: '01.01.2025',
        text: 'Установка водоизмерительного счётчика: кто должен это делать в муниципальной квартире?',
        read: 'Читать',
      },
      {
        id: 40,
        img: '/src/assets/img/article3.png',
        date: '01.01.2025',
        text: 'Установка водоизмерительного счётчика: кто должен это делать в муниципальной квартире?',
        read: 'Читать',
      },
      {
        id: 41,
        img: '/src/assets/img/article3.png',
        date: '01.01.2025',
        text: 'Установка водоизмерительного счётчика: кто должен это делать в муниципальной квартире?',
        read: 'Читать',
      },
      {
        id: 42,
        img: '/src/assets/img/article3.png',
        date: '01.01.2025',
        text: 'Установка водоизмерительного счётчика: кто должен это делать в муниципальной квартире?',
        read: 'Читать',
      },
      {
        id: 43,
        img: '/src/assets/img/article3.png',
        date: '01.01.2025',
        text: 'Установка водоизмерительного счётчика: кто должен это делать в муниципальной квартире?',
        read: 'Читать',
      },
      {
        id: 44,
        img: '/src/assets/img/article3.png',
        date: '01.01.2025',
        text: 'Установка водоизмерительного счётчика: кто должен это делать в муниципальной квартире?',
        read: 'Читать',
      },
      {
        id: 45,
        img: '/src/assets/img/article3.png',
        date: '01.01.2025',
        text: 'Установка водоизмерительного счётчика: кто должен это делать в муниципальной квартире?',
        read: 'Читать',
      },
      {
        id: 46,
        img: '/src/assets/img/article3.png',
        date: '01.01.2025',
        text: 'Установка водоизмерительного счётчика: кто должен это делать в муниципальной квартире?',
        read: 'Читать',
      },
      {
        id: 47,
        img: '/src/assets/img/article3.png',
        date: '01.01.2025',
        text: 'Установка водоизмерительного счётчика: кто должен это делать в муниципальной квартире?',
        read: 'Читать',
      },
      {
        id: 48,
        img: '/src/assets/img/article3.png',
        date: '01.01.2025',
        text: 'Установка водоизмерительного счётчика: кто должен это делать в муниципальной квартире?',
        read: 'Читать',
      },
    ]),
    itemPageItems = ref([
      {
        id: 1,
        img: '/src/assets/img/item-page__item-img.png',
        name: 'Задвижка чугунная КНР 30ч39р Ду50 Ру16',
        article: '123456',
        prevPrice: '1 000',
        currPrice: '2 000',
      },
      {
        id: 2,
        img: '/src/assets/img/item-page__item-img.png',
        name: 'Задвижка чугунная КНР 30ч39р Ду50 Ру16',
        article: '123456',
        prevPrice: '1 000',
        currPrice: '2 000',
      },
      {
        id: 3,
        img: '/src/assets/img/item-page__item-img.png',
        name: 'Задвижка чугунная КНР 30ч39р Ду50 Ру16',
        article: '123456',
        prevPrice: '1 000',
        currPrice: '2 000',
      },
      {
        id: 4,
        img: '/src/assets/img/item-page__item-img.png',
        name: 'Задвижка чугунная КНР 30ч39р Ду50 Ру16',
        article: '123456',
        prevPrice: '1 000',
        currPrice: '2 000',
      },
      {
        id: 5,
        img: '/src/assets/img/item-page__item-img.png',
        name: 'Задвижка чугунная КНР 30ч39р Ду50 Ру16',
        article: '123456',
        prevPrice: '1 000',
        currPrice: '2 000',
      },
      {
        id: 6,
        img: '/src/assets/img/item-page__item-img.png',
        name: 'Задвижка чугунная КНР 30ч39р Ду50 Ру16',
        article: '123456',
        prevPrice: '1 000',
        currPrice: '2 000',
      },
      {
        id: 7,
        img: '/src/assets/img/item-page__item-img.png',
        name: 'Задвижка чугунная КНР 30ч39р Ду50 Ру16',
        article: '123456',
        prevPrice: '1 000',
        currPrice: '2 000',
      },
      {
        id: 8,
        img: '/src/assets/img/item-page__item-img.png',
        name: 'Задвижка чугунная КНР 30ч39р Ду50 Ру16',
        article: '123456',
        prevPrice: '1 000',
        currPrice: '2 000',
      },
      {
        id: 9,
        img: '/src/assets/img/item-page__item-img.png',
        name: 'Задвижка чугунная КНР 30ч39р Ду50 Ру16',
        article: '123456',
        prevPrice: '1 000',
        currPrice: '2 000',
      },
      {
        id: 10,
        img: '/src/assets/img/item-page__item-img.png',
        name: 'Задвижка чугунная КНР 30ч39р Ду50 Ру16',
        article: '123456',
        prevPrice: '1 000',
        currPrice: '2 000',
      },
      {
        id: 11,
        img: '/src/assets/img/item-page__item-img.png',
        name: 'Задвижка чугунная КНР 30ч39р Ду50 Ру16',
        article: '123456',
        prevPrice: '1 000',
        currPrice: '2 000',
      },
      {
        id: 12,
        img: '/src/assets/img/item-page__item-img.png',
        name: 'Задвижка чугунная КНР 30ч39р Ду50 Ру16',
        article: '123456',
        prevPrice: '1 000',
        currPrice: '2 000',
      },
      {
        id: 13,
        img: '/src/assets/img/item-page__item-img.png',
        name: 'Задвижка чугунная КНР 30ч39р Ду50 Ру16',
        article: '123456',
        prevPrice: '1 000',
        currPrice: '2 000',
      },
      {
        id: 14,
        img: '/src/assets/img/item-page__item-img.png',
        name: 'Задвижка чугунная КНР 30ч39р Ду50 Ру16',
        article: '123456',
        prevPrice: '1 000',
        currPrice: '2 000',
      },
      {
        id: 15,
        img: '/src/assets/img/item-page__item-img.png',
        name: 'Задвижка чугунная КНР 30ч39р Ду50 Ру16',
        article: '123456',
        prevPrice: '1 000',
        currPrice: '2 000',
      },
      {
        id: 16,
        img: '/src/assets/img/item-page3__item-img.png',
        name: 'Задвижка чугунная КНР 30ч39р Ду50 Ру16',
        article: '123456',
        prevPrice: '1 000',
        currPrice: '3 000',
      },
      {
        id: 17,
        img: '/src/assets/img/item-page3__item-img.png',
        name: 'Задвижка чугунная КНР 30ч39р Ду50 Ру16',
        article: '123456',
        prevPrice: '1 000',
        currPrice: '3 000',
      },
      {
        id: 18,
        img: '/src/assets/img/item-page3__item-img.png',
        name: 'Задвижка чугунная КНР 30ч39р Ду50 Ру16',
        article: '123456',
        prevPrice: '1 000',
        currPrice: '3 000',
      },
      {
        id: 19,
        img: '/src/assets/img/item-page3__item-img.png',
        name: 'Задвижка чугунная КНР 30ч39р Ду50 Ру16',
        article: '123456',
        prevPrice: '1 000',
        currPrice: '3 000',
      },
      {
        id: 20,
        img: '/src/assets/img/item-page3__item-img.png',
        name: 'Задвижка чугунная КНР 30ч39р Ду50 Ру16',
        article: '123456',
        prevPrice: '1 000',
        currPrice: '3 000',
      },
      {
        id: 21,
        img: '/src/assets/img/item-page3__item-img.png',
        name: 'Задвижка чугунная КНР 30ч39р Ду50 Ру16',
        article: '123456',
        prevPrice: '1 000',
        currPrice: '3 000',
      },
      {
        id: 22,
        img: '/src/assets/img/item-page3__item-img.png',
        name: 'Задвижка чугунная КНР 30ч39р Ду50 Ру16',
        article: '123456',
        prevPrice: '1 000',
        currPrice: '3 000',
      },
      {
        id: 23,
        img: '/src/assets/img/item-page3__item-img.png',
        name: 'Задвижка чугунная КНР 30ч39р Ду50 Ру16',
        article: '123456',
        prevPrice: '1 000',
        currPrice: '3 000',
      },
      {
        id: 24,
        img: '/src/assets/img/item-page3__item-img.png',
        name: 'Задвижка чугунная КНР 30ч39р Ду50 Ру16',
        article: '123456',
        prevPrice: '1 000',
        currPrice: '3 000',
      },
      {
        id: 25,
        img: '/src/assets/img/item-page3__item-img.png',
        name: 'Задвижка чугунная КНР 30ч39р Ду50 Ру16',
        article: '123456',
        prevPrice: '1 000',
        currPrice: '3 000',
      },
      {
        id: 26,
        img: '/src/assets/img/item-page3__item-img.png',
        name: 'Задвижка чугунная КНР 30ч39р Ду50 Ру16',
        article: '123456',
        prevPrice: '1 000',
        currPrice: '3 000',
      },
      {
        id: 27,
        img: '/src/assets/img/item-page3__item-img.png',
        name: 'Задвижка чугунная КНР 30ч39р Ду50 Ру16',
        article: '123456',
        prevPrice: '1 000',
        currPrice: '3 000',
      },
      {
        id: 28,
        img: '/src/assets/img/item-page3__item-img.png',
        name: 'Задвижка чугунная КНР 30ч39р Ду50 Ру16',
        article: '123456',
        prevPrice: '1 000',
        currPrice: '3 000',
      },
      {
        id: 29,
        img: '/src/assets/img/item-page3__item-img.png',
        name: 'Задвижка чугунная КНР 30ч39р Ду50 Ру16',
        article: '123456',
        prevPrice: '1 000',
        currPrice: '3 000',
      },
      {
        id: 30,
        img: '/src/assets/img/item-page3__item-img.png',
        name: 'Задвижка чугунная КНР 30ч39р Ду50 Ру16',
        article: '123456',
        prevPrice: '1 000',
        currPrice: '3 000',
      },
      {
        id: 31,
        img: '/src/assets/img/item-page3__item-img.png',
        name: 'Задвижка чугунная КНР 30ч39р Ду50 Ру16',
        article: '123456',
        prevPrice: '1 000',
        currPrice: '3 000',
      },
      {
        id: 32,
        img: '/src/assets/img/item-page3__item-img.png',
        name: 'Задвижка чугунная КНР 30ч39р Ду50 Ру16',
        article: '123456',
        prevPrice: '1 000',
        currPrice: '3 000',
      },
      {
        id: 33,
        img: '/src/assets/img/item-page4__item-img.png',
        name: 'Задвижка чугунная КНР 30ч39р Ду50 Ру16',
        article: '123456',
        prevPrice: '1 000',
        currPrice: '1 000',
      },
      {
        id: 34,
        img: '/src/assets/img/item-page4__item-img.png',
        name: 'Задвижка чугунная КНР 30ч39р Ду50 Ру16',
        article: '123456',
        prevPrice: '1 000',
        currPrice: '1 000',
      },
      {
        id: 35,
        img: '/src/assets/img/item-page4__item-img.png',
        name: 'Задвижка чугунная КНР 30ч39р Ду50 Ру16',
        article: '123456',
        prevPrice: '1 000',
        currPrice: '1 000',
      },
      {
        id: 36,
        img: '/src/assets/img/item-page4__item-img.png',
        name: 'Задвижка чугунная КНР 30ч39р Ду50 Ру16',
        article: '123456',
        prevPrice: '1 000',
        currPrice: '1 000',
      },
      {
        id: 37,
        img: '/src/assets/img/item-page4__item-img.png',
        name: 'Задвижка чугунная КНР 30ч39р Ду50 Ру16',
        article: '123456',
        prevPrice: '1 000',
        currPrice: '1 000',
      },
      {
        id: 38,
        img: '/src/assets/img/item-page4__item-img.png',
        name: 'Задвижка чугунная КНР 30ч39р Ду50 Ру16',
        article: '123456',
        prevPrice: '1 000',
        currPrice: '1 000',
      },
      {
        id: 39,
        img: '/src/assets/img/item-page4__item-img.png',
        name: 'Задвижка чугунная КНР 30ч39р Ду50 Ру16',
        article: '123456',
        prevPrice: '1 000',
        currPrice: '1 000',
      },
      {
        id: 40,
        img: '/src/assets/img/item-page4__item-img.png',
        name: 'Задвижка чугунная КНР 30ч39р Ду50 Ру16',
        article: '123456',
        prevPrice: '1 000',
        currPrice: '1 000',
      },
      {
        id: 41,
        img: '/src/assets/img/item-page4__item-img.png',
        name: 'Задвижка чугунная КНР 30ч39р Ду50 Ру16',
        article: '123456',
        prevPrice: '1 000',
        currPrice: '1 000',
      },
      {
        id: 42,
        img: '/src/assets/img/item-page4__item-img.png',
        name: 'Задвижка чугунная КНР 30ч39р Ду50 Ру16',
        article: '123456',
        prevPrice: '1 000',
        currPrice: '1 000',
      },
      {
        id: 43,
        img: '/src/assets/img/item-page4__item-img.png',
        name: 'Задвижка чугунная КНР 30ч39р Ду50 Ру16',
        article: '123456',
        prevPrice: '1 000',
        currPrice: '1 000',
      },
      {
        id: 44,
        img: '/src/assets/img/item-page4__item-img.png',
        name: 'Задвижка чугунная КНР 30ч39р Ду50 Ру16',
        article: '123456',
        prevPrice: '1 000',
        currPrice: '1 000',
      },
      {
        id: 45,
        img: '/src/assets/img/item-page4__item-img.png',
        name: 'Задвижка чугунная КНР 30ч39р Ду50 Ру16',
        article: '123456',
        prevPrice: '1 000',
        currPrice: '1 000',
      },
      {
        id: 46,
        img: '/src/assets/img/item-page4__item-img.png',
        name: 'Задвижка чугунная КНР 30ч39р Ду50 Ру16',
        article: '123456',
        prevPrice: '1 000',
        currPrice: '1 000',
      },
      {
        id: 47,
        img: '/src/assets/img/item-page4__item-img.png',
        name: 'Задвижка чугунная КНР 30ч39р Ду50 Ру16',
        article: '123456',
        prevPrice: '1 000',
        currPrice: '1 000',
      },
      {
        id: 48,
        img: '/src/assets/img/item-page4__item-img.png',
        name: 'Задвижка чугунная КНР 30ч39р Ду50 Ру16',
        article: '123456',
        prevPrice: '1 000',
        currPrice: '1 000',
      },
    ])

  const itemsMap = {
    heatMeters: heatMetersItems,
    articles: articlesItems,
    itemPage: itemPageItems,
  }

  const getItems = (section) => {
    return itemsMap[section]
  }

  const sortItemsByPrice = (section, direction = 'asc') => {
    const itemsRef = itemsMap[section]
    if (!itemsRef) {
      return
    }

    const sorted = [...itemsRef.value].sort((a, b) => {
      // Преобразуем строки с пробелами в числа
      const priceA = parseInt(a.currPrice.replace(/\s/g, ''))
      const priceB = parseInt(b.currPrice.replace(/\s/g, ''))

      if (direction === 'asc') {
        return priceA - priceB
      } else {
        return priceB - priceA
      }
    })

    itemsRef.value = sorted
  }

  return {
    heatMetersItems,
    articlesItems,
    itemPageItems,
    itemsMap,
    getItems,
    sortItemsByPrice,
  }
})
